USE master;
GO
ALTER DATABASE DVDLibrary 
SET SINGLE_USER 
WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE DVDLibrary;



CREATE DATABASE DVDLibrary;
USE DVDLibrary;

CREATE TABLE DVD(
	DVDCodeNo NUMERIC(9),
	DVDTitle VARCHAR(40),
	DVDLang VARCHAR(20),
	DVDSubTitles VARCHAR(10),
	DVDPrice NUMERIC(10) 
);

SELECT * FROM DVD;
INSERT INTO DVD VALUES(001,'Vuon sao bang','Korean','Yes',100000);
INSERT INTO DVD VALUES(002,'Me before you','English','Yes',900000);
INSERT INTO DVD VALUES(003,'Ngoi nha hanh phuc','Vietnamese','No',50000);

SELECT MAX(DVDCodeNo) FROM DVD;

SELECT MAX(DVDCodeNo) AS countID FROM DVD;