/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buoi3;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Tran Nhan Nghia
 */
public class DatVeXe extends javax.swing.JFrame {

    /**
     * Creates new form DatVeXe
     */
    public DatVeXe() {
        initComponents();
        loadSTT();
    }

//    ResultSet rs_STT;
//    private void loadSTT() {
//        int i=0;
//        try{
//            String query="SELECT MAX(STT) AS SUM_ID FROM Vexe;";
//            rs_STT=Execute(query);
//            while(rs_STT.next()){
//                i=Integer.valueOf(rs_STT.getString("SUM_ID"));
//            }
//        }catch(Exception ex){
//            System.out.print(ex);
//        }
//        txtSTT.setText(String.valueOf(i+1));
//    }
//    
//    ResultSet rs;
//    Connection connector;
//    private ResultSet Execute(String query){
//        try{
//            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
//            String dbUrl= "jdbc:sqlserver://MSI\\SQLEXPRESS:1433;databaseName=TravelTicket;user=test;password=1234567890";
//            connector=DriverManager.getConnection(dbUrl);
//            PreparedStatement ps=connector.prepareStatement(query);
//            rs=ps.executeQuery();
//        }catch(Exception ex){
//            System.out.println(ex);
//        }
//        
//        return rs;
//    }
    

    private void loadSTT() {
        int i=0;
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String dbUrl= "jdbc:sqlserver://MSI\\SQLEXPRESS:1433;databaseName=TravelTicket;user=test;password=1234567890";
            String query="SELECT MAX(STT) AS SUM_ID FROM Vexe;";
            Connection connector=DriverManager.getConnection(dbUrl);
            PreparedStatement ps=connector.prepareStatement(query);
            ResultSet rs_STT=ps.executeQuery();
            while(rs_STT.next()){
                i=Integer.valueOf(rs_STT.getString("SUM_ID"));
            }
        }catch(Exception ex){
            System.out.print(ex);
        }
        txtSTT.setText(String.valueOf(i+1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtSTT = new javax.swing.JTextField();
        rdbNam = new javax.swing.JRadioButton();
        rdbNu = new javax.swing.JRadioButton();
        cmbDoTuoi = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        txtDienThoai = new javax.swing.JTextField();
        cmbTuyenDuong = new javax.swing.JComboBox<>();
        cmbGio = new javax.swing.JComboBox<>();
        btnHuyBo = new javax.swing.JButton();
        btnDatVe = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        spnNgayDangKy = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        spnNgayKhoiHanh = new javax.swing.JSpinner();
        btnClear = new javax.swing.JButton();
        btnCheck = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("STT");

        jLabel2.setText("Ho va ten");

        jLabel3.setText("Gioi tinh");

        jLabel5.setText("Dia chi");

        jLabel6.setText("Do tuoi");

        jLabel7.setText("Tuyen duong");

        jLabel8.setText("Gio khoi hanh");

        jLabel9.setText("Dien thoai");

        txtSTT.setFocusable(false);

        buttonGroup1.add(rdbNam);
        rdbNam.setText("Nam");
        rdbNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbNamActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbNu);
        rdbNu.setText("Nu");
        rdbNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbNuActionPerformed(evt);
            }
        });

        cmbDoTuoi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "20-30", "30-40", "tren 40" }));

        txtDiaChi.setColumns(20);
        txtDiaChi.setRows(5);
        jScrollPane1.setViewportView(txtDiaChi);

        cmbTuyenDuong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CanTho - ChauDoc", "CanTho- SaiGon" }));

        cmbGio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "3:45", "6:30 " }));

        btnHuyBo.setText("Huy bo");

        btnDatVe.setText("Dat ve");
        btnDatVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatVeActionPerformed(evt);
            }
        });

        jLabel10.setText("Ngay khoi hanh");

        spnNgayDangKy.setModel(new javax.swing.SpinnerDateModel());
        spnNgayDangKy.setEditor(new javax.swing.JSpinner.DateEditor(spnNgayDangKy, "dd/MM//YYYY"));

        jLabel11.setText("Ngay dang ky");

        jSpinner2.setModel(new javax.swing.SpinnerDateModel());
        jSpinner2.setEditor(new javax.swing.JSpinner.DateEditor(jSpinner2, "HH:00"));

        spnNgayKhoiHanh.setModel(new javax.swing.SpinnerDateModel());
        spnNgayKhoiHanh.setEditor(new javax.swing.JSpinner.DateEditor(spnNgayKhoiHanh, "dd/MM//YYYY"));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(rdbNam))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(rdbNu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnNgayKhoiHanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spnNgayDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbGio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(585, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbTuyenDuong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(504, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDatVe))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                                    .addComponent(cmbDoTuoi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtHoTen)
                                    .addComponent(txtSTT))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnHuyBo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSpinner2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCheck, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(55, 55, 55))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtSTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel3)
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cmbDoTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(rdbNam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbNu)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmbTuyenDuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cmbGio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear)
                        .addGap(32, 32, 32)
                        .addComponent(btnCheck)
                        .addGap(26, 26, 26)))
                .addComponent(btnDatVe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(spnNgayDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(spnNgayKhoiHanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnHuyBo))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Calendar cal=Calendar.getInstance();
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtSTT.setText("");
        txtHoTen.setText("");
        rdbNam.setSelected(true);
        cmbDoTuoi.setSelectedIndex(0);
        txtDiaChi.setText("");
        txtDienThoai.setText("");
        cmbGio.setSelectedIndex(0);
        spnNgayDangKy.setValue(cal.getTime());
        spnNgayKhoiHanh.setValue(cal.getTime());
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:
        if(txtHoTen.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Ho Ten Rong", "Dialog",JOptionPane.INFORMATION_MESSAGE);
        }
        if(txtDiaChi.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Dia Chi Rong", "Dialog",JOptionPane.INFORMATION_MESSAGE);
        }
        cal.add(Calendar.DAY_OF_MONTH, 1);
        String ngayDangKy=new SimpleDateFormat("yyyyMMdd").format(spnNgayDangKy.getValue());
        String ngayKhoiHanh=new SimpleDateFormat("yyyyMMdd").format(spnNgayKhoiHanh.getValue());
        int ngayDK=Integer.valueOf(ngayDangKy);
        int ngayKH=Integer.valueOf(ngayKhoiHanh);
        if(ngayKH>=ngayDK){
            JOptionPane.showMessageDialog(this, "Thong tin hop le!");
        }
        else JOptionPane.showMessageDialog(this, "Thong tin khong hop le!");
        
        System.out.println("Ngay dang ky: "+String.valueOf(ngayDangKy));
        System.out.println("Ngay khoi hanh: "+String.valueOf(ngayKhoiHanh));
    }//GEN-LAST:event_btnCheckActionPerformed

    
        private void ExecuteNonQuery(String query, int STT, String Hoten, String Gioitinh, String Dotuoi, String Diachi, String Sodienthoai, String Tuyenduong, String Gio, String Ngaydangky, String Ngaykhoihanh){
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String dbUrl= "jdbc:sqlserver://MSI\\SQLEXPRESS:1433;databaseName=TravelTicket;user=test;password=1234567890";
            Connection connector=DriverManager.getConnection(dbUrl);
            
            PreparedStatement ps=connector.prepareStatement(query);
            ps.setInt(1, STT);
            ps.setString(2, Hoten);
            ps.setString(3, Gioitinh);
            ps.setString(4, Dotuoi);
            ps.setString(5, Diachi);
            ps.setString(6, Sodienthoai);
            ps.setString(7, Tuyenduong);
            ps.setString(8, Gio);
            ps.setString(9, Ngaydangky);
            ps.setString(10, Ngaykhoihanh);
            
            ps.executeUpdate();
        }catch(Exception ex){
            System.out.print(ex);
        }
    }
    
    Connection con;
    private void btnDatVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatVeActionPerformed
        // TODO add your handling code here:
        String query = "INSERT INTO Vexe VALUES (?,?,?,?,?,?,?,?,?,?);";
        int STT=Integer.valueOf(txtSTT.getText());
        String Hoten=txtHoTen.getText();
        String Gioitinh=sex;
        String Dotuoi= cmbDoTuoi.getItemAt(cmbDoTuoi.getSelectedIndex());
        String Diachi=txtDiaChi.getText();
        String Sodienthoai= txtDienThoai.getText();
        String Tuyenduong=cmbTuyenDuong.getItemAt(cmbTuyenDuong.getSelectedIndex());
        String Gio=cmbGio.getItemAt(cmbGio.getSelectedIndex());
        String Ngaydangky=new SimpleDateFormat("yyyy-MM-dd").format(spnNgayDangKy.getValue());
        String Ngaykhoihanh=new SimpleDateFormat("yyyy-MM-dd").format(spnNgayKhoiHanh.getValue());
        
        ExecuteNonQuery(query, STT, Hoten, Gioitinh, Dotuoi, Diachi, Sodienthoai, Tuyenduong, Gio, Ngaydangky, Ngaykhoihanh);
        JOptionPane.showMessageDialog(this, "Đã đăng ký thành công!");
        JOptionPane.showMessageDialog(this, String.valueOf(STT) +" "+ Hoten +" "+ Gioitinh +" "+ Dotuoi +" "+ Diachi +" "+ Sodienthoai +" "+ Tuyenduong +" "+ Gio +" "+ Ngaydangky +" "+ Ngaykhoihanh);
        
    }//GEN-LAST:event_btnDatVeActionPerformed
    
    private String sex;
    private void rdbNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbNamActionPerformed
        // TODO add your handling code here:
        sex="Nam";
    }//GEN-LAST:event_rdbNamActionPerformed

    private void rdbNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbNuActionPerformed
        // TODO add your handling code here:
        sex="Nu";
    }//GEN-LAST:event_rdbNuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatVeXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatVeXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatVeXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatVeXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatVeXe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDatVe;
    private javax.swing.JButton btnHuyBo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbDoTuoi;
    private javax.swing.JComboBox<String> cmbGio;
    private javax.swing.JComboBox<String> cmbTuyenDuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JRadioButton rdbNam;
    private javax.swing.JRadioButton rdbNu;
    private javax.swing.JSpinner spnNgayDangKy;
    private javax.swing.JSpinner spnNgayKhoiHanh;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JTextField txtDienThoai;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtSTT;
    // End of variables declaration//GEN-END:variables

}
